apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    server{
      listen 80;
      index index.php index.html;
      root /usr/share/nginx/html;

      rewrite ^/google$ http://google.com permanent;
    }

  nginx.index: |
    <html>
    <head>
      <title>Code.education Rocks</title>
    </head>
    <body>
      <div style="font-weight:bold; font-size:30px; width:100%; text-align:center;">Code.education Rocks</div>
    </body>
    </html>
